name: Memix CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: read
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        
    - name: Install Rust Toolchain
      uses: dtolnay/rust-toolchain@stable
      
    - name: Install Dependencies
      run: npm install
      working-directory: ./extension
      
    - name: Compile Extension
      run: npm run compile
      working-directory: ./extension
      
    - name: Run Tests
      run: npm test
      working-directory: ./extension
